#!/bin/bash
cat >$1.yaml<<EOF
---
app-id: org.deepin.flatdeb.$1
branch: master
runtime: org.deepin.flatdeb.Base.Platform
runtime-version: unstable
sdk: org.deepin.flatdeb.Base.Sdk
command: $1
writable-sdk: true
appstream-compose: false
separate-locales: false
modules:
  - name: $1
    x-flatdeb-apt-packages:
      - $1
    sources:
      - type: file
        path: deb-buildapi/configure
        dest: '.'
      - type: file
        path: deb-buildapi/Makefile
finish-args:
  - --env=LD_LIBRARY_PATH=/app/lib/x86_64-linux-gnu:/app/lib
  - --env=SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
  - --env=DCONF_USER_CONFIG_DIR=.config/dconf
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --share=network
  - --socket=pulseaudio
  - --talk-name=ca.desrt.dconf
  - --talk-name=org.freedesktop.FileManager1
  - --talk-name=org.freedesktop.portal.Fcitx
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=com.deepin.filemanager.filedialog
  - --filesystem=xdg-run/dconf
  - --filesystem=~/.config/dconf:ro
  - --filesystem=home

rename-icon: $1
rename-desktop-file: $1.desktop
copy-icon: true
...
EOF
gsapp $1
cd /tmp/app/deepin-fpapp-org.deepin.flatdeb.$1* && debuild -us -uc
