#!/bin/sh
flatpak install --system --bundle  /usr/share/deepin-flatpak/app/com.deepin.Screenshot/x86_64/master/bundle
rm /usr/share/deepin-flatpak/app/com.deepin.Screenshot/x86_64/master/bundle
exit 0
