#!/bin/sh
if [ flatpak info --system  com.deepin.ScreenRecorder/x86_64/master >/dev/null 2>&1 ] && [ "$1" = 'remove' ] || [ "$1" = 'purge' ]; then
	flatpak uninstall --system com.deepin.ScreenRecorder/x86_64/master
fi
exit 0
